export const typings = {
  brand: `St. John's Hill Estate Pvt. Ltd.`,
  myPurchases: 'My Orders',
  purchases: 'Orders',
  deposit: 'Top Up Balance',
  home: 'Home',
  shop: 'Shop',
  products: 'Products',
  depositBalance: 'Balance',
  depositBalanceSubTitle: 'Add funds to shop with ease',
  allProducts: 'All Products',
  myProducts: 'My Items',
  withdrawIn24: 'Withdrawals take up to 24 hours',
  amountToWithdraw: 'Withdrawal Amount: 0.00',
  withdrawPlaceholder: 'Enter withdrawal amount',
  withdraw: 'Withdraw',
  withdrawAfterInput: 'Amount to Withdraw',
  enterAmount: 'Enter Amount',
  currency: 'USD',
  yourPurchases: 'Your orders will be displayed here',
  empty: 'Empty',
  cardError: 'Please enter a valid card number',
  withdrawError: 'Withdrawal Error',
  cardNumber: 'Card Number',
  date: 'Date',
  status: 'Status',
  amount: 'Amount',
  noWithdrawals: 'No withdrawals yet',
  emptyHistory: 'No top-up history available',
  balance: 'Balance',
  depostError: 'Top-up Error',
  back: 'Back',
  productBought: 'Added to Cart',
  buyError: 'Purchase Error',
  buy: 'Buy',
  balanceTopUp: 'Your balance has been topped up by',
  goToShopping: 'Go to Shop',
  declined: 'Payment Declined',
  paid: 'Paid',
  transactionLoadError: 'Transaction Load Error',
  addError: 'Error Adding Item',
  addingProduct: 'Adding Product',
  fillAllFields: 'Please fill in all fields',
  emailError: 'Invalid Email',
  authError: 'Authentication Error',
  authorization: 'Sign In',
  yourEmail: 'Your Email',
  password: 'Password',
  recovery: 'Recover password via support',
  login: 'Login',
  noProducts: 'You have no purchased products yet',
  passwordError: 'Password must be at least 8 characters',
  passwordMatchError: 'Passwords do not match',
  registerError: 'Registration Error',
  registration: 'Sign Up',
  confirmPassword: 'Confirm Password',
  noAccount: 'If you don’t have an account, we will create one',
  createAccount: 'Create Account',
  noEmailConfirm: 'Email confirmation is not required',
  balanceSuccess: 'Balance successfully topped up',
  depositError: 'Top-up Error',
  IHavePaid: 'I Have Paid',
  paidOut: 'Paid Out',
  pending: 'Pending',
  newCategory: 'New Category',
  category: 'Category',
  name: 'Name',
  pngError: 'Only JPG/PNG files are allowed.',
  error2mb: 'Image size must not exceed 2MB.',
  enterTitle: 'Enter Title',
  save: 'Save',
  product: 'Product',
  cart: 'Cart',
  addingCart: 'Adding to Cart',
  addingCartDescription: 'You can add items to your cart',
  addToCart: 'Add to Cart',
  price: 'Price',
  quantity: 'Quantity',
  subtotal: 'Subtotal',
  deletedFromCart: 'Removed from Cart',
  cartTotals: 'Cart Totals',
  total: 'Total',
  freeShipping: 'Free Shipping',
  shipping: 'Shipping',
  shippingOptionsDescription: 'Shipping options will be updated at checkout.',
  proccedCheckout: 'Proceed to Checkout',
  billingDetails: 'Billing Details',
  firstName: 'First Name',
  lastName: 'Last Name',
  companyName: 'Company Name (optional)',
  streetAddress: 'Street Address',
  appartment: 'Apartment, suite, unit, etc. (optional)',
  city: 'City',
  country: 'Country',
  postcode: 'Postcode',
  phone: 'Phone',
  emailAddress: 'Email Address',
  county: 'County (optional)',
  differentAddress: 'Ship to a different address?',
  requiredField: 'This field is required.',
  yourOrder: 'Your Order',
  placeOrder: 'Place Order',
  signUpRecommendation: 'Sign Up for a Better Shopping Experience!',
  signUpRecommendationSubTitle: 'Save your favorite items and enjoy exclusive offers.',
}
