export const typings = {
  brand: 'MEGAKOMPYUTER',
  myPurchases: 'Мои покупки',
  purchases: 'Покупки',
  deposit: 'Пополнить баланс',
  home: 'Главная',
  shop: 'Магазин',
  products: 'Скины',
  depositBalance: 'Баланс',
  depositBalanceSubTitle: 'Пополняйте баланс для покупки скинов',
  allProducts: 'Все скины',
  myProducts: 'Мои скины',
  withdrawIn24: 'Вывод средств занимает до 24 часов',
  amountToWithdraw: 'Сумма вывода: 0.00',
  withdrawPlaceholder: 'Введите сумму вывода',
  withdraw: 'Вывести',
  withdrawAfterInput: 'Сумма к выводу',
  enterAmount: 'Введите сумму',
  currency: 'UZS',
  yourPurchases: 'Здесь будут отображаться ваши покупки',
  empty: 'Пусто',
  cardError: 'Введите корректный номер карты',
  withdrawError: 'Ошибка вывода средств',
  cardNumber: 'Номер карты',
  date: 'Дата',
  status: 'Статус',
  amount: 'Сумма',
  noWithdrawals: 'Выводов пока нет',
  emptyHistory: 'История пополнений пуста',
  balance: 'Баланс',
  depostError: 'Ошибка пополнения',
  back: 'Назад',
  productBought: 'Скин куплен',
  buyError: 'Ошибка при покупке',
  buy: 'Купить',
  balanceTopUp: 'Ваш баланс пополнен на',
  goToShopping: 'Перейти в магазин',
  declined: 'Оплата отклонена',
  paid: 'Оплачено',
  transactionLoadError: 'Ошибка загрузки транзакций',
  addError: 'Ошибка добавления',
  addingProduct: 'Добавление скина',
  fillAllFields: 'Заполните все поля',
  emailError: 'Некорректный email',
  authError: 'Ошибка авторизации',
  authorization: 'Авторизация',
  yourEmail: 'Ваш email',
  password: 'Пароль',
  recovery: 'Восстановление пароля через поддержку',
  login: 'Войти',
  noProducts: 'У вас пока нет скинов',
  passwordError: 'Пароль должен содержать минимум 8 символов',
  passwordMatchError: 'Пароли не совпадают',
  registerError: 'Ошибка регистрации',
  registration: 'Регистрация',
  confirmPassword: 'Подтвердите пароль',
  noAccount: 'Если у вас нет аккаунта, мы создадим его',
  createAccount: 'Создать аккаунт',
  noEmailConfirm: 'Подтверждение email не требуется',
  balanceSuccess: 'Баланс успешно пополнен',
  depositError: 'Ошибка пополнения баланса',
  IHavePaid: 'Я оплатил',
  paidOut: 'Выплачено',
  pending: 'В ожидании',
  newCategory: 'Новая категория',
  category: 'Категория',
  name: 'Название',
  pngError: 'Можно загружать только JPG/PNG файлы.',
  error2mb: 'Размер изображения не должен превышать 2MB.',
  enterTitle: 'Введите название',
  save: 'Сохранить',
  product: 'Скин',
}
